#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_92 ]; then
    cd $OPENSHIFT_DATA_DIR
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-linux-x64.tar.gz
    tar xvf *.tar.gz
    rm -f *.tar.gz
fi

export GRADLE=gradle-3.0

if [ ! -d $OPENSHIFT_DATA_DIR/$GRADLE ]; then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/${GRADLE}-bin.zip
    unzip ${GRADLE}-bin.zip
    rm -f ${GRADLE}-bin.zip
fi

cd $OPENSHIFT_REPO_DIR
# $OPENSHIFT_DATA_DIR/$GRADLE/bin/gradle -b build.gradle build -x test
$OPENSHIFT_DATA_DIR/$GRADLE/bin/gradle -g /tmp --version
